#!/bin/bash

clear

echo "╔══════════════════════════════╗"
echo "        SLOWDNS USER PANEL"
echo "╚══════════════════════════════╝"
echo ""
echo "1) Add SSH User"
echo "2) Delete SSH User"
echo "3) Show User Usage"
echo "4) Show All Users"
echo "5) Exit"
echo ""

read -p "Select option: " opt

case $opt in

1)
bash /etc/slowdns-manager/adduser.sh
;;

2)
bash /etc/slowdns-manager/deleteuser.sh
;;

3)
bash /etc/slowdns-manager/usage.sh
;;

4)
cat /etc/slowdns-manager/users.db
;;

5)
exit
;;

*)
echo "Invalid option"
;;

esac
